name: codeflix-admin-api

services:
  app:
    build: .
    image: codeflix-admin-api
    container_name: app
    command: ./.docker/start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8-debian
    container_name: db
    environment:
      - MYSQL_DATABASE=codeflix
      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined

#networks:
#  network:
#    name: codeflix-admin-api
#    driver: bridge