name: codeflix-admin-api-dev

services:
  app:
    build: .
    image: codeflix-admin-api-dev
    container_name: app
    command: ./.docker/start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8-debian
    container_name: db-dev
    environment:
      - MYSQL_DATABASE=codeflix
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

#networks:
#  network:
#    name: codeflix-admin-api-dev
#    driver: bridge